language: bash

sudo: required

os:
    - linux
    - osx

env:
    - BASH=latest
    - BASH=5
    - BASH=4.4
    - BASH=4.3
    - BASH=4.2

services:
    - docker

before_script:
    - |
      if [[ "${TRAVIS_OS_NAME:-}" == "linux" ]]; then
          sudo apt-get install shellcheck
      fi

script:
    - |
      if [[ "${TRAVIS_OS_NAME:-}" == "linux" ]]; then
        shellcheck lib/**/*
      fi

      if [[ "${TRAVIS_OS_NAME:-}" == "linux" && -n "${BASH}" ]]; then
          docker run -v $PWD:/bash bash:$BASH test.sh
      else
          ./test.sh
      fi
