#!/usr/bin/env bash

bs_get_module_const_stub()
{
    printf 'const() { eval "declare -g bs_variable_const_$1=\"$2\""; }'
}

__bs__get_module_var()
{
    __bs__coproc_send "declare | grep '^__bs__var_const_' | sed -e 's/^__bs__var_const_//'"
    __bs__coproc_read
}

__bs__add_module_var()
{
    if declare | grep "^${2}\=" 1>/dev/null 2>&1; then
        printf "Constant '${2}' already exists.\n" 1>&2
        exit 1
    fi

    declare -nr module="${__bs__module_list[${1}]}"
    declare -nr var="${module[var]}"

    if [[ -n "${var[${2}]}" ]]; then
        printf "Duplicate var '${2}' on module '${1}'\n"
        exit 1
    fi

    var["${2}"]="${3}"
}
