#!/usr/bin/env bash
# module

##
#
# Arguments:
#
#   $1 :: The output variable name
#   $2 :: The selection title
#   $@ :: The selection options
##
create()
{
    local output="${1}"; shift
    local title="${1}"; shift
    local value="1"
    local length="${#}"

    printf "%s%s%s\n\n" "${FONT_BOLD}" "${title}" "${FONT_RESET}"

    selection._print "0" "${value}" "${@}"

    while read -rsn1 key; do
        case "${key}" in
            $'\x1b')
                read -rsn1 -t 0.1 tmp
                if [[ "${tmp}" == "[" ]]; then
                    read -rsn1 -t 0.1 tmp
                    case "${tmp}" in
                        "A") # Up
                            if [[ "${value}" -eq 1 ]]; then
                                value="${length}"
                            else
                                value="$(( value - 1 ))"
                            fi
                            ;;
                        "B") #Down
                            if [[ "${value}" -eq "${length}" ]]; then
                                value="1"
                            else
                                value="$(( value + 1 ))"
                            fi
                            ;;
                    esac
                fi
                ;;
            "")
                break
                ;;
        esac

        selection._print "1" "${value}" "$@"
    done

    selection._clear "${length}"

    declare -n var="${output}"
    var="${!value}"
}

selection_value()
{
    if [[ "$1" == "${SELECTION_VALUE}" ]]; then
        return 0
    fi

    return 1
}

_print()
{
    local list_id=1
    local list_age="$1"; shift
    local list_selected="$1"; shift

    if [[ "${list_age}" -ne 0 ]]; then
        printf "\033[%iA" "$#"
    fi

    for item in "$@"; do
        if [[ "${list_id}" == "${list_selected}" ]]; then
            printf "\033[96m"
        fi

        printf "   • %s\n" "${item}"
        printf "\033[0m"
        list_id=$(( list_id + 1 ))
    done
}

_clear()
{
    printf "\033[%iA" "$(( $1 + 1 ))"

    for _ in $(seq 0 "$1"); do
        printf "\r\033[K\n"
    done

    printf "\033[%iA" "$(( $1 + 1 ))"
}
